BOOKS = "books"
READING_LISTS = "reading_lists"
USERS = "users"
CLIENT_ID = "YYafuLHWKYG7Gm6mXqxF9QEEzCQEYDFa"
CLIENT_SECRET = "9GVbXGOxrAGcYS7MrQfILEqEFRsLb4zg9VQKXA5NHOk2r63eZ_Llto91rxHPVYWS"
ALGORITHMS = ["RS256"]
DOMAIN = "dev-8l3axw71ej7xustv.us.auth0.com"
